### ISSUE TITLE
Deprecated Atom APIs will be removed June 1st

### ISSUE THREAD

**Issue by benogle** [peterdotjs/atom-synced-sidebar#3] opened 2015-05-26 23:33 UTC
Atom will no longer load this package after June 1st without changes. There is one deprecation on the latest version (`0.2.3`) of this package:
1. atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use `atom.views.getView(atom.workspace)`, which returns an HTMLElement.

Visit https://gist.github.com/benogle/6d09e295c84b717ef9b4 and search for your package name to see what deprecations are being reported on this package.

See https://github.com/atom/atom/issues/6867 for more info.

**Comment by peterdotjs** [comment] 2015-05-27 14:40
Duplicate of https://github.com/peterdotjs/atom-synced-sidebar/issues/2

**Closed as completed by peterdotjs** 2015-05-27 14:40 UTC
Labels: duplicate
