### ISSUE TITLE
Can't be installed

### ISSUE THREAD

**Issue by Stanzilla** [peterdotjs/atom-synced-sidebar#15] opened 2015-09-25 21:46 UTC
> runas@2.0.0 install C:\Users\Benjamin\AppData\Local\Temp\apm-install-dir-115825-2772-1sg9lr5\node_modules\synced-sidebar\node_modules\pathwatcher\node_modules\runas
> node-gyp rebuild

C:\Users\Benjamin\AppData\Local\Temp\apm-install-dir-115825-2772-1sg9lr5\node_modules\synced-sidebar\node_modules\pathwatcher\node_modules\runas>if not defined npm_config_node_gyp (node "C:\Users\Benjamin\AppData\Local\atom\app-1.0.18\resources\app\apm\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 

gypnpm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\Users\Benjamin\AppData\Local\atom\app-1.0.18\resources\app\apm\bin\node.exe" "C:\Users\Benjamin\AppData\Local\atom\app-1.0.18\resources\app\apm\node_modules\npm\bin\npm-cli.js" "--globalconfig" "C:\Users\Benjamin\.atom\.apm\.apmrc" "--userconfig" "C:\Users\Benjamin\.atom\.apmrc" "install" "C:\Users\Benjamin\AppData\Local\Temp\d-115825-2772-1xmod6m\package.tgz" "--target=0.30.7" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! runas@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

**Comment by peterdotjs** [comment] 2015-09-25 21:51
Duplicate of #13

**Closed as completed by peterdotjs** 2015-09-25 21:51 UTC
